name: 'Serve sneat-go-server' # Frontend uses this GitHub action for end-to-end testing

description: 'Starts a backend server for end-to-end testing of sneat.app in CI-build pipeline'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}"
      shell: bash

    - name: Install GoLang
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: 1.23.2
#        cache-dependency-path: "**/*.sum"


    - name: Serve sneat-go-server
      shell: bash
      working-directory: "${{ github.action_path }}"
#      run: ./serve_gae.sh
      run: |
        ./serve_gae.sh &
        sleep 10

    - name: "Check if sneat-go-server is running"
      shell: sh
      run: curl http://localhost:4300/
