name: Validate action.yml

on:
  push:

jobs:

  verify_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action.yml
        uses: ./
